USE [master]
GO
/****** Object:  Database [JavaAdv]    Script Date: 12.2.2026. 21:06:42 ******/
CREATE DATABASE [JavaAdv]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'JavaAdv', FILENAME = N'Y:\MS SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JavaAdv.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'JavaAdv_log', FILENAME = N'Y:\MS SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JavaAdv_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [JavaAdv] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [JavaAdv].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [JavaAdv] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [JavaAdv] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [JavaAdv] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [JavaAdv] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [JavaAdv] SET ARITHABORT OFF 
GO
ALTER DATABASE [JavaAdv] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [JavaAdv] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [JavaAdv] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [JavaAdv] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [JavaAdv] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [JavaAdv] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [JavaAdv] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [JavaAdv] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [JavaAdv] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [JavaAdv] SET  ENABLE_BROKER 
GO
ALTER DATABASE [JavaAdv] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [JavaAdv] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [JavaAdv] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [JavaAdv] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [JavaAdv] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [JavaAdv] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [JavaAdv] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [JavaAdv] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [JavaAdv] SET  MULTI_USER 
GO
ALTER DATABASE [JavaAdv] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [JavaAdv] SET DB_CHAINING OFF 
GO
ALTER DATABASE [JavaAdv] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [JavaAdv] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [JavaAdv] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [JavaAdv] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [JavaAdv] SET QUERY_STORE = OFF
GO
USE [JavaAdv]
GO
/****** Object:  Table [dbo].[Polaznik]    Script Date: 12.2.2026. 21:06:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Polaznik](
	[PolaznikID] [int] IDENTITY(1,1) NOT NULL,
	[Ime] [nvarchar](100) NULL,
	[Prezime] [nvarchar](100) NULL,
 CONSTRAINT [PK_Polaznik] PRIMARY KEY CLUSTERED 
(
	[PolaznikID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[ProgramObrazovanja]    Script Date: 12.2.2026. 21:06:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProgramObrazovanja](
	[ProgramObrazovanjaID] [int] IDENTITY(1,1) NOT NULL,
	[Naziv] [nvarchar](100) NULL,
	[CSVET] [int] NULL,
 CONSTRAINT [PK_ProgramObrazovanja] PRIMARY KEY CLUSTERED 
(
	[ProgramObrazovanjaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Upis]    Script Date: 12.2.2026. 21:06:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Upis](
	[UpisID] [int] IDENTITY(1,1) NOT NULL,
	[IDPolaznik] [int] NULL,
	[IDProgramObrazovanja] [int] NULL,
 CONSTRAINT [PK_Upis] PRIMARY KEY CLUSTERED 
(
	[UpisID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Upis]  WITH CHECK ADD  CONSTRAINT [FK_Upis_PO] FOREIGN KEY([IDPolaznik])
REFERENCES [dbo].[Polaznik] ([PolaznikID])
GO
ALTER TABLE [dbo].[Upis] CHECK CONSTRAINT [FK_Upis_PO]
GO
ALTER TABLE [dbo].[Upis]  WITH CHECK ADD  CONSTRAINT [FK_Upis_Polaznik] FOREIGN KEY([IDProgramObrazovanja])
REFERENCES [dbo].[ProgramObrazovanja] ([ProgramObrazovanjaID])
GO
ALTER TABLE [dbo].[Upis] CHECK CONSTRAINT [FK_Upis_Polaznik]
GO
/****** Object:  StoredProcedure [dbo].[DohvatiPolaznike]    Script Date: 12.2.2026. 21:06:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[DohvatiPolaznike]
	@POID int
AS
BEGIN
	SELECT p.Ime AS Ime, p.Prezime AS Prezime, po.Naziv AS Program, po.CSVET AS Bodovi FROM Upis u
	INNER JOIN Polaznik p ON p.PolaznikID = u.IDPolaznik
	INNER JOIN ProgramObrazovanja po ON u.IDProgramObrazovanja = po.ProgramObrazovanjaID
	WHERE u.IDProgramObrazovanja = @POID
END
GO
/****** Object:  StoredProcedure [dbo].[NoviUpis]    Script Date: 12.2.2026. 21:06:42 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC [dbo].[NoviUpis]
	@PolaznikID int, @POID int
AS
BEGIN
	INSERT INTO Upis VALUES (@PolaznikID, @POID)
END
GO
USE [master]
GO
ALTER DATABASE [JavaAdv] SET  READ_WRITE 
GO
